# File describing colours used in the application.
# Needs sorting out
#
scheme = "dark"
# GENERAL COLOURS
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
SOFT_WHITE = (211, 219, 213)
RED = (255, 0, 0)
BLUE = (0, 0, 255)
YELLOW = (252, 255, 48)
IVORY4 = (139, 130, 131)
LIGHT_GREY = (211, 211, 211)
MID_GREY = (138, 138, 138)
DARK_GREY = (64, 64, 64)
GREEN = (0, 235, 0)
DARK_GREEN = (0, 100, 0)
V_DARK_GREEN = (0, 45, 0)
LIME_GREEN = (50, 205, 50)
FOREST_GREEN = (34, 139, 34)


if scheme == "dark":
    STARTCOLOUR = BLACK
    TEXT_INSTRU = (58, 64, 86)
    TEST_BG = (227, 223,213)
    RPM_MSB_TXT = GREEN
    RPM_LSB_TXT = V_DARK_GREEN
    GAUGE_BORDER_COLOUR = LIGHT_GREY
    MAIN_BORDER_COLOUR = MID_GREY
    SECTION_BORDER_COLOUR = DARK_GREY
    TRACE_LINE_COL = DARK_GREEN
    TRACE_PEAK_COL = RED
    TABLE_CELL_COL = DARK_GREY

elif scheme == "light":
    STARTCOLOUR = SOFT_WHITE
    TEXT_INSTRU = (58, 64, 86)
    TEST_BG = (227, 223,213)
    RPM_MSB_TXT = GREEN
    RPM_LSB_TXT = V_DARK_GREEN
    GAUGE_BORDER_COLOUR = BLACK
    MAIN_BORDER_COLOUR = MID_GREY
    SECTION_BORDER_COLOUR = BLACK
    TRACE_LINE_COL = DARK_GREEN
    TRACE_PEAK_COL = RED
    TABLE_CELL_COL = DARK_GREY

else:
    TEXT_BG = RED


# Reuse of colour setup, must be at the end!
TEXT_BG = STARTCOLOUR
GEN_BACKGROUND = STARTCOLOUR
SCROLL_WIPE_COL = GEN_BACKGROUND
DIAL_GAUGE_WIPE_COL = GEN_BACKGROUND